#!/bin/bash
set -euo pipefail

# Setup code signing for MacAgentWatch
# Usage: bash scripts/setup-signing.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
XCCONFIG_DIR="$PROJECT_ROOT/app/MacAgentWatch"
LOCAL_XCCONFIG="$XCCONFIG_DIR/Local.xcconfig"

echo "=== MacAgentWatch Code Signing Setup ==="
echo ""

# Check if Local.xcconfig already exists
if [ -f "$LOCAL_XCCONFIG" ]; then
    echo "Local.xcconfig already exists at: $LOCAL_XCCONFIG"
    echo "Edit it directly to update signing settings."
    echo ""
    cat "$LOCAL_XCCONFIG"
    exit 0
fi

# Prompt for team ID
echo "This script creates a Local.xcconfig file for code signing."
echo "You can find your Development Team ID in:"
echo "  1. Xcode > Preferences > Accounts > Your Apple ID"
echo "  2. Apple Developer Portal > Membership"
echo ""

read -rp "Development Team ID (or press Enter to skip): " TEAM_ID
read -rp "Code Sign Identity (default: Apple Development): " SIGN_IDENTITY

SIGN_IDENTITY="${SIGN_IDENTITY:-Apple Development}"

# Create Local.xcconfig
cat > "$LOCAL_XCCONFIG" << EOF
// Local.xcconfig
// Local code signing overrides (DO NOT COMMIT)
// Generated by scripts/setup-signing.sh

DEVELOPMENT_TEAM = ${TEAM_ID}
CODE_SIGN_IDENTITY = ${SIGN_IDENTITY}
EOF

echo ""
echo "Created: $LOCAL_XCCONFIG"
echo ""
echo "Contents:"
cat "$LOCAL_XCCONFIG"
echo ""
echo "NOTE: Local.xcconfig is excluded from git via .gitignore"
